
import React from 'react';

const ProjectStructure: React.FC = () => {
  return (
    <div className="bg-gray-800 text-gray-300 p-4 rounded-lg border border-gray-700 font-mono text-sm leading-relaxed">
      <div className="flex items-center gap-2 mb-2 text-blue-400 font-bold border-b border-gray-700 pb-2">
        <i className="fa-solid fa-folder-open"></i>
        <span>fake-news-ai/</span>
      </div>
      <div className="pl-4 space-y-1">
        <div className="flex items-center gap-2">
          <i className="fa-solid fa-folder text-yellow-500"></i>
          <span>data/</span>
          <span className="text-gray-500 ml-2 italic"># Place news.csv here</span>
        </div>
        <div className="pl-6 text-gray-400">
          <div className="flex items-center gap-2">
            <i className="fa-solid fa-file-csv text-green-500"></i>
            <span>news.csv</span>
          </div>
        </div>
        
        <div className="flex items-center gap-2">
          <i className="fa-solid fa-folder text-yellow-500"></i>
          <span>model/</span>
          <span className="text-gray-500 ml-2 italic"># Auto-generated by train.py</span>
        </div>
        
        <div className="flex items-center gap-2">
          <i className="fa-brands fa-python text-blue-400"></i>
          <span>train.py</span>
        </div>
        <div className="flex items-center gap-2">
          <i className="fa-brands fa-python text-blue-400"></i>
          <span>explain.py</span>
        </div>
        <div className="flex items-center gap-2">
          <i className="fa-brands fa-python text-blue-400"></i>
          <span>app.py</span>
        </div>
        <div className="flex items-center gap-2">
          <i className="fa-solid fa-list-check text-purple-400"></i>
          <span>requirements.txt</span>
        </div>
        <div className="flex items-center gap-2">
          <i className="fa-solid fa-info-circle text-gray-400"></i>
          <span>README.md</span>
        </div>
      </div>
    </div>
  );
};

export default ProjectStructure;
